server:
  port: 18081
spring:
  application:
    name: goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.88.2:3306/changgou_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  redis:
    host: 192.168.88.2 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 20000
workerId: 0
datacenterId: 0
# Redis数据库索引（默认为0）
#  spring.redis.database=0
  # Redis服务器地址
#  spring.redis.host=192.168.88.2
  # Redis服务器连接端口
#  spring.redis.port=6379
  # Redis服务器连接密码（默认为空）
#  spring.redis.password=
  # 连接池最大连接数（使用负值表示没有限制） 默认 8
#  spring.redis.lettuce.pool.max-active=8
  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#  spring.redis.lettuce.pool.max-wait=-1
  # 连接池中的最大空闲连接 默认 8
#  spring.redis.lettuce.pool.max-idle=8
  # 连接池中的最小空闲连接 默认 0
#  spring.redis.lettuce.pool.min-idle=0